apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: supabase
spec:
  selector:
    app: storage
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: supabase/storage-api:v1.0.7
          env:
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: ANON_KEY
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SERVICE_ROLE_KEY
            - name: POSTGREST_URL
              value: "http://postgrest:3000"
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: JWT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: STORAGE_DB_URL
            - name: REGION
              value: "local"
          ports:
            - containerPort: 5000
