apiVersion: v1
kind: Service
metadata:
  name: pgmeta
  namespace: supabase
spec:
  selector:
    app: pgmeta
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgmeta
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgmeta
  template:
    metadata:
      labels:
        app: pgmeta
    spec:
      containers:
        - name: pgmeta
          image: supabase/pg-meta:v0.80.0
          env:
            - name: PG_META_PORT
              value: "8080"
            - name: PG_META_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_HOST
            - name: PG_META_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PORT
            - name: PG_META_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_DB
            - name: PG_META_DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_USER
            - name: PG_META_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
